### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 9840380** [MiroHibler/sublime-keymaps#32]
command: find_keymap
Exception in thread Thread-36:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 765, in run
    rendered = list(self.renderer.format(keymaps))
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 710, in format
    packages = sorted(packages, key=key_func)
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 438, in extract
    keyMaps = self.getKeymaps()
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 352, in getKeymaps
    if not key_token[0]:
IndexError: list index out of range

command: cheat_sheet
Exception in thread Thread-38:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 765, in run
    rendered = list(self.renderer.format(keymaps))
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 629, in format
    packages = sorted(packages, key=key_func)
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 438, in extract
    keyMaps = self.getKeymaps()
  File "/Users/z/Library/Application Support/Sublime Text/Installed Packages/Keymaps.sublime-package/sublime_keymaps.py", line 352, in getKeymaps
    if not key_token[0]:
IndexError: list index out of range

**Comment by MiroHibler** [comment]
I'm not maintaining this plugin anymore as I moved away from Sublime a few years ago, sorry :(

**Comment by 9840380** [comment]
Thanks. and what are you using now? Neovim?
